name: "Shared workflow"

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
        default: elev
  workflow_dispatch:
    inputs:
      app:
        type: choice
        default: elev
        required: true
        options:
        - elev
        - sas
    

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo input
        run: echo ${{ inputs.app }}
