name: "Shared workflow"

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        default: elev

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo input
        run: echo ${{ github.event.inputs.app }}
