name: Test Action

on:

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: app-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'staging' }}

    env:
      bucket: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production' && 'static' || 'static-staging' }}
      
    steps:
      - name: Check existence
        id: exists
        run: |
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" -I https://static-test.asku.no/bbc81f1215534fa92c696d3fa7a47beef59c5330.manifest.json)
          echo "Status code: $status_code"
          if [ "$status_code" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run next step only if file does not exist
        if: steps.check_file.outputs.exists == 'false'  # Using the id to reference the previous step's output
        run: echo "File does not exist, running the next step."

      - name: Skip if file exists
        if: steps.check_file.outputs.exists == 'true'  # Using the id to reference the previous step's output
        run: echo "File exists, skipping the next step.
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Echo bucket name
        run: echo ${{ env.bucket }}

      - name: Echo group
        run: echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production' && format('{0}-{1}', github.workflow, 'production') || format('{0}-{1}', github.workflow, github.ref) }}

      - name: Set year
        run: echo "year=$(date +'%Y')" >> "$GITHUB_ENV"

      - name: Echo year
        run: echo $year
  reuse:
    needs: [test-job]
    uses: ./.github/workflows/ias.yml
    with:
      app: sas
