name: Test Action

on:

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: app-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'staging' }}

    env:
      bucket: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production' && 'static' || 'static-staging' }}
      
    steps:
      - name: Echo bucket name
        run: echo ${{ env.bucket }}

      - name: Echo group
        run: echo ${{ github.workflow }}-${{ github.ref }}${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && '-' }}${{ github.event_name == 'push' && 'staging' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment || '' }}
      
