name: Test Action

on:

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: app-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'staging' }}

    env:
      bucket: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production' && 'static' || 'static-staging' }}
      
    steps:
      - name: Echo bucket name
        run: echo ${{ env.bucket }}

      - name: Echo group
        run: echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production' && format('{0}-{1}', github.workflow, 'production') || format('{0}-{1}', github.workflow, github.ref) }}

      - name: Set year
        run: echo "year=$(date +'%Y')" >> "$GITHUB_ENV"

      - name: Echo year
        run: echo $year

      - name: Run shared
        uses: ./.github/workflows/shared.yml
        with:
          app: sas
